### ISSUE TITLE
Not found on registry

### ISSUE THREAD

**Issue by awbait** [widcardw/mdit-plugin-callouts#1]
Hello! I love that you are doing this! I also use Obsidian as a markdown editor. When I tried to install, I got an error:
![image](https://user-images.githubusercontent.com/12417799/194839870-ef6bdc4f-3b4d-447a-8f4a-099ea63208d5.png)

**Comment by widcardw** [comment]
Maybe it's the problem of the package name. It's `mdit-plugin-callouts`, not `callout`. Sometimes I also mix them up...😂

**Comment by awbait** [comment]
damn, really! fix it later in the readme, thanks!

**Comment by widcardw** [comment]
Already fixed! Thanks for raising this issue and correcting my mistakes!
