### ISSUE TITLE
Problem with import css

### ISSUE THREAD

**Issue by awbait** [widcardw/mdit-plugin-callouts#2]
I installed the plugin, then added this line to my file docs/.vitepress/config.js
```
import CalloutPlugin from 'mdit-plugin-callouts';
```
![image](https://user-images.githubusercontent.com/12417799/194848871-190874dc-12ca-4c43-b17f-7f6083cb32fb.png)
and it seems to work, but I still need to connect css, I add the line
```
import 'mdit-plugin-callouts/index.css';
```
and then i get an error
![image](https://user-images.githubusercontent.com/12417799/194848799-cb6a4875-d2a6-48e4-a862-19297868fa1e.png)

**Comment by widcardw** [comment]
Maybe you should not import it in _docs/.vitepress/config.js_. 

According to [vitepress docs](https://vitepress.vuejs.org/guide/theme-introduction#using-a-custom-theme), you should enable a custom theme by adding the file _docs/.vitepress/theme/index.js_, and my config is 

```ts
// docs/.vitepress/theme/index.js
import DefaultTheme from "vitepress/theme";
import 'mdit-plugin-callouts/index.css';  // <-- css files should be imported here

export default {
    ...DefaultTheme,
    enhanceApp({ app }) {
        // ...
    },
}
```

**Comment by widcardw** [comment]
Additionally, I have changed some style and updated the version to `v1.0.2`. This version looks better than previous versions. 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/55699713/194865034-b9acbf7b-952c-44b7-8bb7-e3ae4f1fadaa.png">

**Comment by widcardw** [comment]
I should add some tips to readme so that anyone would like to use this plugin in vuepress or vitepress. Thanks for reporting the issues!

**Comment by awbait** [comment]
Works. It would be cool if they had the same style as [custom vitepress containers](https://vitepress.vuejs.org/guide/markdown#custom-containers). But even without that, it's great! Thank you.



![image](https://user-images.githubusercontent.com/12417799/194871284-e81bdc3d-bf4b-435f-abc6-a63d04d91699.png)

**Comment by widcardw** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/55699713/194903619-a05668e6-d651-4e1d-afed-3118e30ec0d7.png">

Callouts of vitepress theme is available now! Just change it into

```ts
import 'mdit-plugin-callouts/vp.css'
```
